### ISSUE TITLE
Create unit tests

### ISSUE THREAD

**Issue by khenderick** [khenderick/zfs-snap-manager#15]
Write unit tests to make sure that functionality keeps working as expected. When fixing bugs, I can then write test to reproduce and validate the fix. This makes testing a lot faster than my current approach, which is usually to run the changes a few days on all my ZFS nodes.

**Comment by stevleibelt** [comment]
From my knowledge of other development languages, I know that replacing inline created dependencies (like [`today = datetime.now()`](https://github.com/khenderick/zfs-snap-manager/blob/master/scripts/clean.py#L40) is part of the game to make code testable.
I also see some lines like `logger = None  # To be overwritten by Manager.init_logger()` which should be either instantiated as NullLogger (logger object that is actually not logging but implements the logger interface).
Am I right with my thought in the python world?

I will try to read a bit how to write [Unit tests](https://docs.python.org/3/library/unittest.html) in python for educational reasons and see how things are going.

**Comment by stevleibelt** [comment]
Damn, now it's almost a year ago. Right after September, expected family "things" had happend and took way more free time that I've calculated naively.

FTL: I've tried things but ended up running against the "python 2 is not suppored, please rewrite stuff in python 3" or "please use latest version of your used libraries" wall.

**Comment by khenderick** [comment]
I'm closing this issue as I unfortunately don't have the time anymore to maintain ZFS Snapshot Manager. I would like to point you towards the awesome tool [zrepl](https://zrepl.github.io/) which has nearly all of ZFS Snapshot Manager's features and much more.

In any case, thanks for being a part of this community.
