### ISSUE TITLE
Minimum retention in a bucket

### ISSUE THREAD

**Issue by pjoubert-** [khenderick/zfs-snap-manager#19]
This is not necessarily a bug, I guess it should be discussed in some way.

I'll just take an example to illustrate. Let's assume that the retention is 0d0w0m1y

At day 1, there is one snapshot.

At day 300, there is still one snapshot, 300 days old, and that's ok.

At day 337, the snapshot just comes out of retention, is erased, and a new snapshot comes, but is  now 1 day old!  Is that such retention we want to keep with a "1y" retention flag ?

Is my understanding of the code ok ?

My expectation will be to get one snapshot running along the current year, and one that is a year old that is kept until the newest is transferred in the years bucket.

A way to implement that can be to just add one to each bucket that is not 0.

Or maybe it can be explained in the Readme that a bucket keep a snapshot that is below it's age.

**Comment by khenderick** [comment]
Your understanding is correct. Basically, the code just creates the requested buckets and places them next to eachother. Then the snapshots are placed in the bucket that corresponds with their age. After that, the oldest from each snapshot is kept.

An important thing to understand is that all buckets are placed one after the other, and each bucket has a "width" (the year bucket has a 336 days width). So in the case of 0d0w0m1y, there's only one bucket, starting from the first day, till day 336. Every snapshot will end up in this year bucket immediately.

Some (simplified) ascii art (don't mind exact day numbers):

0d0w0m1y
    now --- (year bucket) --- day 335 --- (deleted after this)

1d1w1m1y
    now --- (day bucket) --- day 0 --- (week bucket) --- day 7 --- (month bucket) --- day 35 --- (year bucket) --- day 371 --- (deleted after this)

For example, 7d3w11m4y says: For 7 days, I want to keep 1 snapshot per day. After that, the remaining snapshot should be kept at a ration of 1 per week for 3 weeks long. From then on, 1 snapshot per month for 11 months, and then 4 more at 1 per year. The total span of the 7d3w11m4y schema is thus 5 years.

I don't like your suggested possible implementation too much as in this case, this would at a certain point in time cause a snapshot of about 2 years old, while the user specified only 1 year. I think - and that's your other suggestion/remark - it's more the documentation that is lacking, or maybe the need for another interpretation of the schema (where the user can e.g. choose between the two).

Anyway, I'm going to let this rest for a few more days, thinking about possible options. In any case, feel free to add more suggestions or correct me where I did not completely understand the issue.

**Comment by pjoubert-** [comment]
Your reply is just as clear as I could have imagined.

I took an extreme example to put in perspective the effective behavior of this buckets.

I find the idea of using buckets to handle a progressive retention really neat and just wanted to make clear for everyone how long they would keep their snapshots, and let them define it according to their needs.

Thanks for the reply !
