### ISSUE TITLE
replication not working fails with exception

### ISSUE THREAD

**Issue by WinndyBoy** [khenderick/zfs-snap-manager#21]
I've gotten it to work, but wanted to share what my problem was...

it seems the test for size of the replication in zfs.pl ">&1 > /dev/null" was causing the command to return an error, without that it seems to work fine....

I changed 
command = '{0} 2>&1 > /dev/null | grep \'total estimated size is\''.format(command)
to
 command = '{0} | grep \'total estimated size is\''.format(command)

**Comment by khenderick** [comment]
This was fixed by @tylerjl in #20.

**Comment by WinndyBoy** [comment]
woops, didn't notice that

**Comment by khenderick** [comment]
No problem, the pull request was not yet merged in back when you created the ticket.
