### ISSUE TITLE
Recursive snapshots

### ISSUE THREAD

**Issue by korobkov** [khenderick/zfs-snap-manager#22]
Hello and thank you for this very useful tool!

Could you, please, also support an option for taking, replicating and cleaning recursive snapshots?
This could be useful to operate on the whole trees of zvols or filesystems instead of configuring them one by one…

thanks in advance,
Andrey

**Comment by stevleibelt** [comment]
@korobkov I support your open feature request.
Especially since I browsed to this very useful tool to ask for exactly the same feature request.

Thanks in advance

Stev

**Comment by mmeidlinger** [comment]
+1 from my side. 
@khenderick: Do you see any major blockers for this feature this? If not, I might have a look on how to implement it.

**Comment by khenderick** [comment]
I don't think there would be any issues with making them recursive, it would certainly make maintaining complex datasets easier. Feel free to implement them and make a PR.
