### ISSUE TITLE
resend unsuccessfully replicated snapshots

### ISSUE THREAD

**Issue by SlothOfAnarchy** [khenderick/zfs-snap-manager#23]
First of all, great tool! I'm about to configure it for all my machines.

I found one problem though: if replication of a snapshot failed, it won't be retransmitted.
In my case it failed because I used a non-root user on the receiving side when pushing snapshots (for now I just added sudo to the receive commands). But I imagine the same thing could happen if the connection is lost while transmitting snapshots.

I propose renaming the snapshots before and after transmitting, e.g. calling them 20161206_local when creating them and renaming them to 20161206 when the transfer is finished successfully. _local snapshots could then be retransmitted and should not be cleaned in the meantime.

Thanks in advance!

**Comment by khenderick** [comment]
I was under the impression that if a certain snapshot could not be replicated for whatever reason, it would just be retried on the next run (e.g. the next day). Did you see such thing?

It's on my todo list to tag the last "common" snapshot, so they don't get removed if replication would fail for a longer time.

**Comment by SlothOfAnarchy** [comment]
That's possible, I didn't wait for the next run, I just restarted the service and it didn't try resending the failed snapshots.
I had to destroy the snapshot and restart the service for it to retry.

If the daemon will retry sending on the next run then that's certainly enough.

**Comment by khenderick** [comment]
Each run does more or less the following for each configured dataset/volume:
* Is it time to process this dataset? (the trigger)
* Take the snapshot
* Replicate it if required
* Clean the snapshots

If it bails out during replication, it won't retry it that day, as during the next run it notices a snapshot is already taken today (or the trigger isn't present), and continues with the other datasets. However, next day, it will need to take action again (taking the snapshot), and will then notice the previous one hasn't been replicated, so it will replicate that one, together with the new one.

Leaving this open though, as it might be better to re-try more often.

**Comment by khenderick** [comment]
Going to close this, as having it fixed automatically the next run is OK for me
