### ISSUE TITLE
wait till scrub done?

### ISSUE THREAD

**Issue by avi9526** [khenderick/zfs-snap-manager#24]
Hi

Does this script wait till scrub is done or it will create snapshots anyway (which probably invoke scrub stop or some problem)?
Is there plans to make it wait until scrub stop?

Thnx

**Comment by SlothOfAnarchy** [comment]
Creating a snapshot while the pool scrubs is no problem. Deleting snapshots can impact performance though.

The scrub process is not being checked when a snapshot is created. I also don't think it would be a good idea, as some scrubs take days, depending on drive performance and pool size.

**Comment by khenderick** [comment]
A late answer, but I indeed don't want to wait too long for taking snapshots. I have a 12TB pool, and it can take a long time before it finishes.
