### ISSUE TITLE
zero length snapshots

### ISSUE THREAD

**Issue by Hr46ph** [khenderick/zfs-snap-manager#29]
Did a search but couldn't find this being asked previously.

Some of my datasets change very little and making regular snapshots result in multiple zero byte snapshots.

Is there a way, or would you consider this a feature request, to have zfs-snap-manager not make a new snapshot if the previous one is zero bytes? Other options would be to change its name to the current date, or remove it and make a new one.

Either way, I am now creating scripts to perform maintenance for something that I believe would be better suited by zfs-snap-manager.

Thanks!

**Comment by stevleibelt** [comment]
@Hr46ph did you make any progress in your own maintenance scripts?
First idea is to use the `postexec` section or extend the existing `Clean.py`. I also have some datasets fitting into your issue description.

**Comment by Hr46ph** [comment]
> @Hr46ph did you make any progress in your own maintenance scripts?
> First idea is to use the `postexec` section or extend the existing `Clean.py`. I also have some datasets fitting into your issue description.

No, but I have since moved to [Sanoid](https://github.com/jimsalterjrs/sanoid/), more features and more actively developed. I've submitted the same request there and for now I either remove them manually or ignore them.

Its not an issue per se, zfs doesn't care. So its purely cosmetic and for usability (cleaner list).

**Comment by khenderick** [comment]
I'm closing this issue as I unfortunately don't have the time anymore to maintain ZFS Snapshot Manager. I would like to point you towards the awesome tool [zrepl](https://zrepl.github.io/) which has nearly all of ZFS Snapshot Manager's features and much more.

In any case, thanks for being a part of this community.
