### ISSUE TITLE
How to install it on Ubuntu server 18.04

### ISSUE THREAD

**Issue by l2fl2f** [khenderick/zfs-snap-manager#33]
Dear,

I tried to install it on my Ubuntu server 18.04 but what's the packages names for all dependencies ?

On FreeBSD no problem but with apt not the same story...

Thx

**Comment by khenderick** [comment]
The dependencies are:
* `zfs` (obviously)
* `python 2.7`
* `openssh`
* `mbuffer`
* `python2-daemon`
