### ISSUE TITLE
ZFS encryption

### ISSUE THREAD

**Issue by Typhonragewind** [khenderick/zfs-snap-manager#38]
Any plans for implementing sending encrypted streams and receive as encrypted on an untrusted remote machine? 
For example:

`zfs send tank/test@snap1 | ssh -p 2345 my.remote.server zfs recv -o encryption=on -o keyformat=passphrase -o keylocation=file:///path/to/keyfile`

And maybe adding the options o the config ini as

encrypt = True/False
passphrase = mypassphrase

**Comment by khenderick** [comment]
I'm closing this issue as I unfortunately don't have the time anymore to maintain ZFS Snapshot Manager. I would like to point you towards the awesome tool [zrepl](https://zrepl.github.io/) which has nearly all of ZFS Snapshot Manager's features and much more.

In any case, thanks for being a part of this community.
