### ISSUE TITLE
Move on to python3?

### ISSUE THREAD

**Issue by sulaweyo** [khenderick/zfs-snap-manager#39]
I'm using zfs-snap-manager since ages for all my backups but as arch moved python2 to AUR and it's really out of support at this point I wanted to ask if there are any plans to move zfs-snap-manager to python3.

**Comment by khenderick** [comment]
I certainly understand your concern. Unfortunately, there's not much time I can spend on this project, so I'm looking whether the awesome project [zrepl](https://zrepl.github.io/) can potentially replace this project.

I hope to find some time to validate this and to write a migration guide for the current users of zfs-snap-manager.

**Comment by sulaweyo** [comment]
Fully valid thank you for the response. I'll have a look on zrepl
