### ISSUE TITLE
Made replication of custom snapshots optional

### ISSUE THREAD

**Issue by khenderick** [khenderick/zfs-snap-manager#9]
It turned out (pull-request #8) that the tool replicates custom snapshots as well (so not only the ones created by the tool, following the yyyymmdd notation). However, it might be better to make that configurable.

**Comment by SlothOfAnarchy** [comment]
I filtered snapshots fitting to the date scheme in https://github.com/khenderick/zfs-snap-manager/commit/4e038216b18665feffea2080e766f2197b05856a, it's not optional though.

**Comment by khenderick** [comment]
I'm closing this issue as I unfortunately don't have the time anymore to maintain ZFS Snapshot Manager. I would like to point you towards the awesome tool [zrepl](https://zrepl.github.io/) which has nearly all of ZFS Snapshot Manager's features and much more.

In any case, thanks for being a part of this community.
